# Generated by Django 2.1 on 2018-08-08 16:42

from django.db import migrations, models
import django.db.models.deletion
import trackapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CS096',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=100)),
                ('ecms_link', models.URLField(blank=True)),
                ('request_date', models.DateTimeField(auto_now=True)),
                ('requestor', models.CharField(max_length=100)),
                ('approver', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('group', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[(trackapp.models.PrivActions('Grant'), 'Grant'), (trackapp.models.PrivActions('Deny'), 'Deny')], max_length=10)),
                ('priv', models.CharField(choices=[(trackapp.models.Privs('Read'), 'Read'), (trackapp.models.Privs('Modify'), 'Modify')], max_length=10)),
                ('cs096', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackapp.CS096')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=100, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[(trackapp.models.UserActions('Add'), 'Add'), (trackapp.models.UserActions('Remove'), 'Remove')], max_length=10)),
                ('group', models.CharField(max_length=100)),
                ('cs096', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackapp.CS096')),
            ],
        ),
    ]
