# Generated by Django 2.1 on 2018-08-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs096',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackapp.Product'),
        ),
        migrations.AlterField(
            model_name='cs096',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackapp.Protocol'),
        ),
    ]
