# Generated by Django 2.1 on 2018-08-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0002_auto_20180810_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cs096',
            name='ecms_link',
        ),
        migrations.AlterField(
            model_name='cs096',
            name='approver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cs096',
            name='requestor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
