# Generated by Django 2.1 on 2018-08-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0003_auto_20180810_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileshare',
            name='action',
            field=models.CharField(choices=[(1, 'Grant'), (2, 'Deny')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='priv',
            field=models.CharField(choices=[(1, 'Modify'), (1, 'Read')], max_length=10),
        ),
    ]
