# Generated by Django 2.1 on 2018-08-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0004_auto_20180810_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileshare',
            name='action',
            field=models.CharField(choices=[('Grant', 1)], max_length=10),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='priv',
            field=models.CharField(choices=[('Modify', 1)], max_length=10),
        ),
    ]
