# Generated by Django 2.1 on 2018-08-16 02:22

from django.db import migrations, models
import trackapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0005_auto_20180810_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='action',
            field=models.CharField(choices=[('Add', trackapp.models.UserActions('Add')), ('Remove', trackapp.models.UserActions('Remove'))], max_length=10),
        ),
    ]
